apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-appointment-app
  template:
    metadata:
      labels:
        app: doctor-appointment-app
    spec:
      containers:
      - name: php-app-container
        image: latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: LoadBalancer
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
